name: Run Shell Command

on:
  push:
    branches:
      - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a Shell Command
      run: |
        echo "Hello, this is a shell command."
      